name: Build and deploy Python app to Azure Web App - docteract

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python version
              uses: actions/setup-python@v1
              with:
                  python-version: "3.10"

            - name: Create and start virtual environment
              run: |
                  python -m venv venv
                  source venv/bin/activate
              working-directory: ./backend

            - name: Install dependencies
              run: pip install -r requirements.txt
              working-directory: ./backend

            # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

            - name: Zip artifact for deployment
              run: zip -r release.zip .
              working-directory: ./backend

            - name: Upload artifact for deployment jobs
              uses: actions/upload-artifact@v3
              with:
                  name: python-app
                  path: backend/release.zip

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v3
              with:
                  name: python-app

            - name: Unzip artifact for deployment
              run: unzip release.zip
              working-directory: ./backend

            - name: "Deploy to Azure Web App"
              uses: azure/webapps-deploy@v2
              id: deploy-to-webapp
              with:
                  app-name: "docteract"
                  slot-name: "Production"
                  publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_17C7E64E1C3F4C00B61637B41D57FBDE }}
